import { AbsoluteFill, Audio, Sequence, interpolate, staticFile, useCurrentFrame, useVideoConfig } from "remotion";
import { C, ease } from "./theme";
import { Finish, Glow, Grid } from "./components/Backdrop";
import { Footage, Highlight, Window, WINDOW, VWINDOW } from "./components/Footage";
import { Caption } from "./components/Caption";
import { Hook } from "./scenes/Hook";
import { Logo } from "./scenes/Logo";
import { BendTime } from "./scenes/BendTime";
import { Stats } from "./scenes/Stats";
import { Outro } from "./scenes/Outro";
import { CAPTIONS, CARDS, DURATION, SHOTS, WIN_END, WIN_START } from "./timeline";

export const DEBUT_DURATION = DURATION;

const useVertical = () => {
  const { width, height } = useVideoConfig();
  return height > width;
};

const WindowLayer: React.FC = () => {
  const frame = useCurrentFrame(); // local to the window sequence
  const vertical = useVertical();
  const win = vertical ? VWINDOW : WINDOW;
  const enter = interpolate(frame, [0, 40], [0, 1], { extrapolateRight: "clamp", easing: ease.out });
  const back = interpolate(frame, [CARDS.stats.from - WIN_START, CARDS.stats.from + 27 - WIN_START], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp", easing: ease.inOut });
  return (
    // Portrait: window sits high so captions get their own space underneath
    <AbsoluteFill style={{ perspective: 2200, alignItems: "center", justifyContent: vertical ? "flex-start" : "center", paddingTop: vertical ? 130 : 0 }}>
      <div
        style={{
          transform: `translateY(${(1 - enter) * 240}px) rotateX(${(1 - enter) * 26}deg) scale(${(0.84 + 0.16 * enter) * (1 - back * 0.08)})`,
          opacity: enter,
          filter: back > 0 ? `blur(${back * 10}px)` : undefined,
          transformStyle: "preserve-3d",
        }}
      >
        <Window w={win.w} h={win.h}>
          {SHOTS.map((s, i) => (
            <Sequence key={i} from={s.from - WIN_START} durationInFrames={s.dur} layout="none">
              <Footage src={s.src} trimSec={s.trim} width={win.w} height={win.h} keys={vertical ? s.vkeys : s.keys} fit={vertical ? "cover" : "width"}>
                {s.highlights?.map((h, j) => <Highlight key={j} {...h} />)}
              </Footage>
            </Sequence>
          ))}
        </Window>
      </div>
    </AbsoluteFill>
  );
};

export const Debut: React.FC = () => (
  <AbsoluteFill style={{ background: C.bg }}>
    <Grid opacity={0.045} />
    <Glow y="100%" opacity={0.1} size={1200} />

    <Sequence from={WIN_START} durationInFrames={WIN_END - WIN_START}>
      <WindowLayer />
    </Sequence>

    {CAPTIONS.map((c, i) => (
      <Sequence key={i} from={c.from} durationInFrames={c.dur}>
        <Caption {...c} />
      </Sequence>
    ))}

    <Sequence from={CARDS.hook.from} durationInFrames={CARDS.hook.dur}>
      <Hook />
    </Sequence>
    <Sequence from={CARDS.logo.from} durationInFrames={CARDS.logo.dur}>
      <Logo dur={CARDS.logo.dur} />
    </Sequence>
    <Sequence from={CARDS.bendTime.from} durationInFrames={CARDS.bendTime.dur}>
      <BendTime dur={CARDS.bendTime.dur} />
    </Sequence>
    <Sequence from={CARDS.stats.from} durationInFrames={CARDS.stats.dur}>
      <Stats dur={CARDS.stats.dur} />
    </Sequence>
    <Sequence from={CARDS.outro.from} durationInFrames={CARDS.outro.dur}>
      <Outro dur={CARDS.outro.dur} />
    </Sequence>

    <Finish />

    {/* Music + sound effects, generated by audio/generate.mjs from this same timeline */}
    <Audio src={staticFile("audio/soundtrack.mp3")} />
  </AbsoluteFill>
);
